name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          PUBLIC_INSTANT_APP_ID: ${{ secrets.PUBLIC_INSTANT_APP_ID }}
          PUBLIC_R2_ACCOUNT_ID: ${{ secrets.PUBLIC_R2_ACCOUNT_ID }}
          PUBLIC_R2_ACCESS_KEY_ID: ${{ secrets.PUBLIC_R2_ACCESS_KEY_ID }}
          PUBLIC_R2_SECRET_ACCESS_KEY: ${{ secrets.PUBLIC_R2_SECRET_ACCESS_KEY }}
          PUBLIC_R2_BUCKET_NAME: ${{ secrets.PUBLIC_R2_BUCKET_NAME }}
          PUBLIC_R2_REGION: ${{ secrets.PUBLIC_R2_REGION }}
          PUBLIC_R2_ENDPOINT: ${{ secrets.PUBLIC_R2_ENDPOINT }}
          PUBLIC_PLATFORM_DOMAIN: ${{ secrets.PUBLIC_PLATFORM_DOMAIN }}
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: storefront
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
